version: '3'
services:
  server:
    container_name: server
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - PORT=3000
      - JWT_SECRET=boquita2023
      - DATABASE_URL=mysql://root:12345678@db:3306/ecommerce
    volumes:
      - './server:/app'
      - '/app/node_modules'
    networks:
      - e-commerce
  client:
    container_name: client
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    depends_on:
      - server
    ports:
      - "4000:4000"
    environment:
      - SERVER_URL=http://server:3000/api/v1/
    volumes:
      - './client:/app'
      - '/app/node_modules'
    networks:
      - e-commerce
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=ecommerce
      - MYSQL_ROOT_PASSWORD=12345678
    networks:
      - e-commerce
networks:
  e-commerce:
