version: '3'
services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ./server/.env
    networks:
      - e-commerce
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    depends_on:
      - server
    ports:
      - "4000:4000"
    env_file:
      - ./client/.env
    networks:
      - e-commerce
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=ecommerce
    networks:
      - e-commerce
networks:
  e-commerce:
