# Seleccionamos la imagen base de Node.js
FROM node:18

# Establecemos el directorio de trabajo
WORKDIR /app

# Copiamos los archivos de configuración y dependencias
COPY package*.json ./

RUN npm install

# Instalamos las dependencias
COPY . .

# Fix para prisma
RUN npx prisma generate

# Exponemos el puerto donde se ejecuta el servidor
EXPOSE 3000

# Ejecutamos el servidor
CMD ["npm", "run", "dev"]
