# Seleccionamos la imagen base de Node.js
FROM node:16

# Establecemos el directorio de trabajo
WORKDIR /app

# Copiamos los archivos de configuración y dependencias
COPY package*.json tsconfig.json ./

RUN npm install

# Instalamos las dependencias
COPY . .

# Exponemos el puerto donde se ejecuta el servidor
EXPOSE 3000

# Ejecutamos el servidor
CMD ["npm", "run", "dev"]
